DROP TABLE IF EXISTS T_CHANGE_SPEC_ITEM;
DROP TABLE IF EXISTS T_CHANGE_SPEC;
DROP TABLE IF EXISTS T_FIRM;

CREATE T_FIRM_HISTORY
(
    FIRM_HISTORY_ID   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FIRM_ID           INT UNSIGNED NOT NULL,
    FIRM_NAME         VARCHAR(50) NOT NULL,
    PARENT_FIRM_NAME  VARCHAR(50),
    VALID_FROM        DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
);

CREATE TABLE T_CHANGE_SPEC
(
  
);

CREATE TABLE T_CHANGE_SPEC_ITEM
(
  
);

CREATE TABLE T_STAGING
(
  
);

CREATE TABLE T_DATA_CENTER
(
    DATA_CENTER_HISTORY_ID   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DATA_CENTER_ID           INT UNSIGNED NOT NULL,
    DATA_CENTER_NAME          VARCHAR(50) NOT NULL,
    VALID_FROM                DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
);

CREATE TABLE T_CAGE
(
    CAGE_HISTORY_ID   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CAGE_ID           INT UNSIGNED NOT NULL,
    DATA_CENTER_ID    INT UNSIGNED NOT NULL,
    CAGE_NAME         VARCHAR(50) NOT NULL,
    VALID_FROM        DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
  
);

CREATE TABLE T_RACK
(
  
    VALID_FROM                DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
);

CREATE TABLE T_DEVICE_TYPE
(
  
    VALID_FROM                DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
);

CREATE TABLE T_DEVICE
(
  
    VALID_FROM                DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
);

CREATE TABLE T_PORT
(
  
    VALID_FROM                DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
);

CREATE TABLE T_CROSS_CONNECT_TYPE
(
  
    VALID_FROM                DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
);

CREATE TABLE T_CROSS_CONNECT
(
  
    VALID_FROM                DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
);

CREATE TABLE T_MARKET_DATA_FEED_TYPE
(
  
    VALID_FROM                DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
);

CREATE TABLE T_MARKET_DATA_FEED
(
  
    VALID_FROM                DATE NOT NULL,
    VALID_TO          DATE,
    APPLIED_AT        DATETIME NOT NULL,
    APPLIED_BY        VARCHAR(50),
    ACTION            VARCHAR(50)
);
