spring.application.name=dcim-server

spring.datasource.url=jdbc:mariadb://localhost:3306/dcim
spring.datasource.username=dcim_user
spring.datasource.password=abc.123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=com.dcim.UpperSnakeCaseNamingStrategy
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.contexts=demo
